import { FiEdit2, FiEye, FiTrash2 } from "react-icons/fi";
import { Link } from "react-router-dom";
import { Badge } from "../../components/ui/badge.tsx";
import { Button } from "../../components/ui/button.tsx";
import { formatMoney } from "../../lib/money.ts";
import type { ProductListItem } from "../../types/models.ts";

export function ProductTable({ products, canWrite, canDelete, onDelete, deletingId }: { products: ProductListItem[]; canWrite: boolean; canDelete: boolean; onDelete: (product: ProductListItem) => void; deletingId?: string | null }) {
 return <div className="overflow-x-auto"><table className="w-full min-w-220 text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">Product</th><th className="px-3 py-3">Brand</th><th className="px-3 py-3">Price</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Created</th><th className="px-3 py-3 text-right">Actions</th></tr></thead><tbody>{products.map((product) => <tr key={product.id} className="border-b border-slate-100 last:border-0"><td className="px-3 py-4"><Link to={`/products/${product.id}`} className="font-medium text-slate-900 hover:text-blue-600">{product.name}</Link><div className="mt-0.5 text-xs text-slate-500">{product.sku}</div></td><td className="px-3 py-4 text-slate-600">{product.brand?.name ?? "—"}</td><td className="px-3 py-4 font-medium text-slate-700">{formatMoney(product.price, product.currency)}</td><td className="px-3 py-4"><Badge variant={product.isActive ? "success" : "default"}>{product.isActive ? "Active" : "Inactive"}</Badge></td><td className="px-3 py-4 text-slate-500">{new Date(product.createdAt).toLocaleDateString()}</td><td className="px-3 py-4"><div className="flex justify-end gap-1"><Link aria-label={`View ${product.name}`} to={`/products/${product.id}`}><Button size="sm" variant="ghost"><FiEye /></Button></Link>{canWrite && <Link aria-label={`Edit ${product.name}`} to={`/products/${product.id}/edit`}><Button size="sm" variant="ghost"><FiEdit2 /></Button></Link>}{canDelete && <Button aria-label={`Delete ${product.name}`} size="sm" variant="ghost" className="text-red-600" disabled={deletingId === product.id} onClick={() => onDelete(product)}><FiTrash2 /></Button>}</div></td></tr>)}</tbody></table></div>;
}
